version: '3.9'

services:
  webserver:
    # My Computer
    # image: 'nginx:stable-alpine'
    # Raspberry Pi
    image: 'arm64v8/nginx:latest'
    container_name: nginx
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    environment: 
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    restart:
      always

#  repository:
#    image: 'sonatype/nexus3:3.30.0'
#    container_name: nexus
#    restart:
#      always

  jenkins:
    image: 'jenkins/jenkins:latest'
    container_name: jenkins
    # WIP Reverse proxy with nginx
    restart:
      always

#  sonar:
#    image: 'sonarqube:7.9.6-community'
#    container_name: sonar
#    restart:
#      always

volumes:
  nginx_configuration:

networks:
  devops: