version: '3.9'

services:
  # https://github.com/klo2k/nexus3-docker/blob/master/Dockerfile
  repository:
    image: 'sonatype/nexus3:3.30.0'
    container_name: delirio_nexus
    networks:
      - proxy
    ports:
      - "8081:8081"
    volumes:
      - './nexus/data:/nexus-data'
    environment:
      - NEXUS_CONTEXT=nexus
    restart: 
      unless-stopped

  # https://docs.sonarqube.org/latest/setup/get-started-2-minutes/
  sonar:
    image: 'sonarqube:community'
    container_name: delirio_sonarqube
    networks:
      - proxy
    ports:
      - "9000:9000"
    volumes:
      - './sonar/conf/delirio.sonar.properties:/opt/sonarqube/conf/sonar.properties'
    #   - './sonar/data:/opt/sonarqube/data'
    #   - './sonar/logs:/opt/sonarqube/logs'
    #   - './sonar/extensions:/opt/sonarqube/extensions'
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    restart: 
      unless-stopped

networks: 
  proxy:
    name: delirio_network