version: '3.9'

services:
  jenkins:
    container_name: delirio_jenkins
    image: 'jenkins/jenkins:latest'
    networks:
      - proxynet
    # WIP Reverse proxy with nginx
    restart:
      unless-stopped

networks: 
  delirio_network: