version: '3.9'

services:
  webserver:
    container_name: delirio_nginx
    image: 'nginx:1.19'
    networks:
      - proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/pages:/usr/share/nginx/html:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    environment:
      API_HOST: ${DELIRIO_HOST}
    restart: 
      always

networks: 
  proxy:
    name: delirio_network